# Generated by Django 3.0 on 2020-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200412_1816'),
        ('users', '0002_moviepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepreference',
            name='movie_liked',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
