# Generated by Django 3.0 on 2020-04-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_moviepreference_movie_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepreference',
            name='movie_liked',
        ),
    ]
