# Generated by Django 3.0 on 2020-04-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_user_liked'),
        ('users', '0004_remove_moviepreference_movie_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepreference',
            name='favorite_movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
