# Generated by Django 3.0 on 2020-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_user_liked'),
        ('users', '0005_moviepreference_favorite_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepreference',
            name='favorite_movie',
        ),
        migrations.AddField(
            model_name='moviepreference',
            name='favorite_movie',
            field=models.ManyToManyField(default='', to='movies.Movie'),
        ),
    ]
