# Generated by Django 3.0 on 2020-04-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200416_0624'),
        ('users', '0007_auto_20200416_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepreference',
            name='favorite_movie',
            field=models.ManyToManyField(default=None, to='movies.Movie'),
        ),
    ]
