# Generated by Django 3.0 on 2020-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('name', models.TextField()),
                ('alias', models.TextField(null=True)),
                ('actors', models.TextField()),
                ('cover', models.TextField(null=True)),
                ('directors', models.TextField()),
                ('douban_score', models.FloatField()),
                ('douban_votes', models.IntegerField()),
                ('imdb_id', models.TextField()),
                ('languages', models.TextField()),
                ('mins', models.IntegerField()),
                ('official_site', models.TextField(null=True)),
                ('regions', models.TextField()),
                ('release_date', models.TextField()),
                ('storyline', models.TextField()),
            ],
        ),
    ]
