# Generated by Django 3.0 on 2020-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_moviepreference_movie_liked'),
        ('movies', '0006_auto_20200412_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_liked',
            field=models.ManyToManyField(to='users.MoviePreference'),
        ),
    ]
