# Generated by Django 3.0 on 2020-04-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_user_liked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-douban_votes', '-douban_score']},
        ),
    ]
